version: "3.9"

services:
  broker:
    image: rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: "rabbitmqctl await_startup"
      interval: 1s
      timeout: 30s
      retries: 3
      start_period: 1s


  adminapi:
    build: ./adminAPI
    command: ./start.sh
    ports:
      - "8000:8000"
    # volumes:
    #   - ./adminAPI:/app
    depends_on:
      broker:
        condition: service_healthy


  clientapi:
    build: ./clientAPI
    command: ./start.sh
    ports:
      - "9000:9000"
    # volumes:
    #   - ./clientAPI:/app
    depends_on:
      broker:
        condition: service_healthy

